version: 1.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    cd src

    nuget restore

    cd ..
build:
  verbosity: minimal
before_package:
- cmd: 
deploy:
- provider: NuGet
  api_key:
    secure: Uft/AgWL0ObDUb6hWLhsftRR1sNhLa5vONUcVa/2KjVAYZApxZD6ckJ+ABFQs3bB
  skip_symbols: true
  artifact: /.*\.nupkg/